### ISSUE TITLE
Add dark theme logo to the readme

### ISSUE THREAD

**Issue by OldStarchy** [cooltronicpl/Craft-document-helpers#11]
The image in the readme looks bad when viewed with the dark theme on GitHub.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/15243523/165663816-8e1f4310-3794-4052-8dbc-729a5c89b782.png">

From [the GitHub Basic formatting syntax docs](
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) you can add `#gh-dark-mode-only` or `#gh-light-mode-only` to selectively show images depending on the color theme.

> Context | URL
> -- | --
> Dark Theme | `![GitHub Light](https://github.com/github-light.png#gh-dark-mode-only)`
> Light Theme | `![GitHub Dark](https://github.com/github-dark.png#gh-light-mode-only)`

**Comment by cooltronicpl** [comment]
Added black theme logo with an update to Craft 4 on a bump with many typo fixes in version 1.0.1
