### ISSUE TITLE
Craft 4.0 support

### ISSUE THREAD

**Issue by arentsen** [cooltronicpl/Craft-document-helpers#12]
Loving the plugin! Can we expect an update for Craft 4.0 compatibility?

**Comment by cooltronicpl** [comment]
I planned to push an update. But now it is alive faster for your request, we are waiting only for an update in the CraftCMS store.
You can install a plugin through composer in the 1.0.1 version.
MPDF for PHP8.x needs a GD extension.
Version 0.0.x. (now 0.0.7) is last for Craft 3.
Version 1.0.0 and up is for Craft 4.
Could you write if the plugin works properly after updating to Craft CMS 4?
Now plugins are working similarly for versions 3 (0.0.x) and 4 (1.0.x), but I need confirmation if is everything working properly after the update from Craft v3 to v4. Read me updated instructions are equivalent for both versions.

**Comment by arentsen** [comment]
That's great! I am currently not able to upgrade to Craft 4.0 because I am waiting for a few more plugins to offer compatibility. When I am, I will let you know. Thanks for your efforts.
