### ISSUE TITLE
FileHelper class not found after updating from 1.1.1 to 1.2.2

### ISSUE THREAD

**Issue by TomDeSmet** [cooltronicpl/Craft-document-helpers#18]
`Class "cooltronicpl\documenthelpers\variables\FileHelper" not found`

PDF generating stopped working after update. Needed to roll back to 1.1.1

Using Craft CMS 4.4.15

**Comment by cooltronicpl** [comment]
Resolved in 1.2.3 by importing `craft\helpers\FileHelper`.
