### ISSUE TITLE
date option not working

### ISSUE THREAD

**Issue by d-karstens** [cooltronicpl/Craft-document-helpers#19]
Hi, 

We've run into an issue where our PDF files are not updating when using the `date` option on version 1.2.5

I believe it's because of the `$attributes['date'] ?? false` check on this line https://github.com/cooltronicpl/Craft-document-helpers/blob/master/src/variables/DocumentHelperVariable.php#L51C16-L51C16

Changing it to `isset($attributes['date'])` like it used to be in an older version seems to work

Thanks!

**Comment by cooltronicpl** [comment]
Please try now in `1.3.0` for v4 and `0.4.0` for v3 also we made other changes that caused a problem in the code because the exact change caused a problem when we used the header and the footer in PDFs in some of our tests.

**Comment by d-karstens** [comment]
Yep, it's working for us on version `1.3.0` :+1:
Thank you for the fix!
