### ISSUE TITLE
Entry Data not populating in template

### ISSUE THREAD

**Issue by brandondeweese** [cooltronicpl/Craft-document-helpers#2]
I can't get any data from simple fields in entry, such as entry.slug, to appear in the generated pdf. But oddly, I'm able to return fields with arrays. Am i missing something here?

```
	<a href="{{siteUrl}}{{craft.documentHelper.pdf('blog/_pdf.twig', 'file', 'document.pdf', entry, '' )}}" target="_blank">Download

</a>
```

![Screen Shot 2021-09-01 at 7 11 37 AM](https://user-images.githubusercontent.com/18017918/131687030-31c7da76-932e-4e08-b33c-1ce31676617b.png)

**Comment by cooltronicpl** [comment]
We added a custom field to parse some variables which aren't passed by Craft when you pass from an array-like entry and you have only variables from CMS. Now we can pass in a custom field in attribute an array, number, date, or string. This was described in README on the 0.0.6 version.
