### ISSUE TITLE
pdfAsset with extra custom asset field

### ISSUE THREAD

**Issue by masiorama** [cooltronicpl/Craft-document-helpers#21]
Hello, thanks for your plugin.
I have a question: is it possible to generate pdf as assets with pdfAsset passing also custom fields?
For instance, my pdf volume has also another custom field _catalogPdfType_ that is useful for me to get also the type of the asset once I want to read the asset, because with the same generation process I have to create 3 different files which have slight differences.

![asset](https://github.com/cooltronicpl/Craft-document-helpers/assets/731916/c52547d6-fa5e-4672-b1aa-f2b698c454f2)

I read the entire doc and I wasn't able to find any suggestion.
Thanks in advance!

**Comment by masiorama** [comment]
I guess something should be done around [here](https://github.com/cooltronicpl/Craft-document-helpers/blob/343bfca919efa1a6c95504ccdbe08f525ba8f2dc/src/variables/DocumentHelperVariable.php#L240).

**Comment by cooltronicpl** [comment]
So is it possible to run `pdfAsset` three times?
That should generate three absolutely independent documents with other styling, volumes, or templates.

**Comment by masiorama** [comment]
Yup, I skipped the pdfEntry with a dummy one, passed via custom prop all the needs, therefore create 3 different links. It works, even if I skypped entirely the catalogPdfType field.
