### ISSUE TITLE
Prevent pagebreak in div

### ISSUE THREAD

**Issue by ghost** [cooltronicpl/Craft-document-helpers#25]
If a div, for example at the bottom of a page, doesn't fit as a whole on the page, you should be able to add an option to prevent a pagebreak within this div. The pagebreak should happen right before this div.

**Comment by cooltronicpl** [comment]
Utilizing the PDF Generator plugin, you can now leverage the mPDF HTML property to control page breaks. Implement it with the following CSS parameter:

```HTML
<div style="page-break-inside: avoid;">
    <!-- Insert your non-breakable content here -->
</div>
```
Can you test this property to confirm its effectiveness?

**Comment by ghost** [comment]
It works great, thanks!
