### ISSUE TITLE
Images don't render

### ISSUE THREAD

**Issue by brandondeweese** [cooltronicpl/Craft-document-helpers#3]
Is there a trick to getting images in the pdf template? <img> tag does not seem to work.

**Comment by cooltronicpl** [comment]
We used another plugin called Image Toolbox by craft-starter to get the image:: https://plugins.craftcms.com/image-toolbox
We updated information about the image tricks in the README.

**Comment by cooltronicpl** [comment]
The next trick is to embed img URL in src with img tag.
We updated README.
