### ISSUE TITLE
Change the head title of PDF document

### ISSUE THREAD

**Issue by parwinderD4D** [cooltronicpl/Craft-document-helpers#4]
Hi, could you please let me know how I can change the head title for the pdf document?

## My PDF HTML  Code
Please ceck my HTML code 
![image](https://user-images.githubusercontent.com/46927214/136794053-24272c54-230b-4614-b9eb-51e24b5aca8e.png)

Code for download PDF

![image](https://user-images.githubusercontent.com/46927214/136794599-3ae49c04-2f58-4ae5-840f-1bd4b75fb991.png)

This is what I am getting in the output : 
![image](https://user-images.githubusercontent.com/46927214/137841928-4cc37097-c588-42cc-9c59-75cad0317286.png)

Any idea how I can replace or change this text.

Looking forward

**Comment by cooltronicpl** [comment]
This is a fragment of code for title handling::
`
if(isset($variables['title'])) $pdf->SetTitle($variables['title']);
`
This should add a variable that will change the title:
`
{% set pdfOptions = { 
...,
title: "The title" } %}
`

**Comment by parwinderD4D** [comment]
Thanks for the quick reply,
`{% set pdfOptions = { ..., title: "The title" } %}`
It's not working, As I have reviewed the plugin code where the **title** is getting from **$variables** not from the **$attributes** . 
![image](https://user-images.githubusercontent.com/46927214/136817485-23f151da-cb78-4feb-9979-9177778c1ac9.png)

![image](https://user-images.githubusercontent.com/46927214/136818104-246a48e7-6998-45ce-bf34-96ea16ca28ae.png)
due to this title is not override

if I modify the code
`if(isset($attributes['title'])){ 
            $pdf->SetTitle($attributes['title']);
 } else if(isset($variables['title'])){
            $pdf->SetTitle($variables['title']);
 }`
 Then only custom **Title** override in pdf 
 
 could you please update this code in the plugin?
 
 Looking forward

**Comment by cooltronicpl** [comment]
We added in version 0.0.6 a custom attribute of the title, described in the README.
