### ISSUE TITLE
No Styles in PDF

### ISSUE THREAD

**Issue by joshparylak** [cooltronicpl/Craft-document-helpers#8]
I've got the PDF generating, but my custom styles for the template are not working.

I've tried a stylesheet in a <link> tag and just pasting the styles on the template in a <style> tag. PDF generates unstyled either way.

**Comment by cooltronicpl** [comment]
I'm using only styles in a tag.
Many times it works.
I'm including style tags on the top of a twig template file.
Sometimes it needs fixing of some assets like the width of Bootstrap original CSS in included generated documents in examples in the Store.
Sometimes I have a strange problems with a grid and flexbox.
